dist: trusty
sudo: required
language: bash
before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2020-02/run.sh |
  bash
notifications:
  slack:
    secure: BRm2H7J5xzuxIzXyOhyL+nR1G/HETXvPLvHG6fYmqqQ0ZIOFWa3fjWvxQS7Dq4iGMVJ+IMvALlDSzpS0R7PSMp+j0781AffbmFdmuAZQDfspiJGaCfR7up19o7xkC6X0MXcsNhkR0YpdelQxGhaXleKbOoEVpjb9D3ywbakjIiWE4bELiZrZhrehYKFm2rmpz9q0GauwZdqZHIc9vPvtFNNe4DPS+/axUnJ8kmenr2ZsuohCYx6afJWjprv4/3GK39Jr+K3h8cOUIVnD0yFAAKVQmhI3sfWZ+4y4gnBoTFEcTq11pyvAl/JoZoSDEAZJ81gURi98xJyYY2tHSt78T2ZNgl5oivFkZvtVw/1gdExx08Sln6Ok3FRpWXjVBlPFNWMxCEL4cMCVAjpW/tQHWTeIeIv+wPu0mhVirc/pwuJwJ7eNDCHu/s6dkpSrqtYbTywj0W3OLSuVWNATou6WSObihG+8wnQhnUSMW0M+JrKa2WBL6kfShVLg4Ltgyu0nvX/DofOcuNDEAJfFB4ihn5b7WFsrUFnjma2Eetm6j0mlovziJxbKmVwnlEvt0JhkCmAuCgdLEvBbLFvGVba6Emvv22/2/RUt+Su478brqhyoFt2IhxbhNavu46a6+CbTNa1laHnePL1SVzC9YR4DWwPYHiQ4HilF0kOZ4kEjxBE=
